# Auto-label PRs

"documentation":
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - CONTRIBUTING.md
          - README.md

"migration":
  - changed-files:
      - any-glob-to-any-file:
          - docs/migration/**
          - migration/matraix/**
